### ISSUE TITLE
Wish: support filtering geocoding to a bounding box.

### ISSUE THREAD

**Issue by markstos** [StephanGeorg/geocoder-arcgis#1]
It would be nice if there was an option to specify a bounding box to be used with geocoding, so that results outside the bounding box would be considered geocode failures.

I did not find this feature documented as being in the ArcGIS online gecoder, so it needs to be implemented now in client libraries. 

This library could perhaps use coordinatesContainsPoint to check results as they come back.

**Comment by markstos** [comment]
Oops, looks like like the latest version of the upstream API does support this, and you already support passing in the option, it's just highlighted in the README.   Closing this request.

https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm#ESRI_SECTION1_E7214BD3ADA34C50A2B88C08F253DF41

**Comment by StephanGeorg** [comment]
Yes, this is what you need: Specify a bounding box w/ bbox https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm#ESRI_SECTION3_24A68CF5D6E54FDE810E243227052A0A.
