### ISSUE TITLE
wish: implement geocodeAddresses

### ISSUE THREAD

**Issue by markstos** [StephanGeorg/geocoder-arcgis#4]
The bulk geocode method 'geocodeAddresses' is documented to exist, but there are no tests for it, and the code to construct the proper query seems to be missing. A manual test of the example shown in the README returned a 200. 

Also, the method is designed for /bulk/ geocoding, yet the example showed passing only a single string to the method. I would presume an array would be accepted. 

There may be some code of interest to borrow from [geoservices-js](https://github.com/Esri/geoservices-js) which has a working client for this REST endpoint.

**Comment by StephanGeorg** [comment]
I will add the feature. Right now I get strange responses from the API...

**Comment by StephanGeorg** [comment]
@markstos would you please test it, if it fits your needs? I have no usecase for that feature. I will add "findAddressCandidates" the next days.
