### ISSUE TITLE
Add custom endpoints

### ISSUE THREAD

**Issue by StephanGeorg** [StephanGeorg/geocoder-arcgis#6]
The default endpoint is https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/. When I run my own service, the endpoints are

`http://<catalog-url>/<serviceName>/GeocodeServer`

**suggest**: `http://geocodeservice-url/suggest`
**findAddressCandidates**: `http://<geocodeservice-url>/findAddressCandidates`
**reverseGeocode**: `http://<geocodeservice-url>/reverseGeocode`
**geocodeAddresses**: `http://<geocodeservice-url>/geocodeAddresses`

And **find** is the same like **geocodeAddresses** ?

Would you guys @jgravois  @markstos please clarify?

**Comment by jgravois** [comment]
my favorite explanation of the differences between `/find` and `/findAddressCandidates` can be found [here](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find-address-candidates.htm)

> Note: The ArcGIS Online World Geocoding Service offers two different operations that allow you to geocode one location at a time:
> 
> **find** —Pass the input location as a single line of text.
> Example: text=380 New York Street, Redlands, CA 92373
> 
> **findAddressCandidates** - Parse the input location using multiple parameters.
> For example, Address=380 New York Street&City=Redlands&Region=CA&Postal=92373
> OR
> Pass the input location as a single line of text.
> For example, singleLine=380 New York Street, Redlands, CA 92373
> 
> The recommended operation to use is **findAddressCandidates**. Single field input is easier because the address parsing is done for you; however, multifield input may provide faster responses and more precise results.

[`/geocodeAddresses`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-geocode-addresses.htm) is for batch geocoding.

**Comment by StephanGeorg** [comment]
Now I got it:

`/find?text="380 New York Street, Redlands, CA 92373"`

gets the same response like

`/findAddressCandidates?singleLine="380 New York Street, Redlands, CA 92373"`

Thanks for explanation.
